// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_K
arma::mat build_K(int T);
RcppExport SEXP _mhpfilter_build_K(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(build_K(T));
    return rcpp_result_gen;
END_RCPP
}
// hp_trend
arma::vec hp_trend(const arma::vec& x, const arma::mat& A, double lambda);
RcppExport SEXP _mhpfilter_hp_trend(SEXP xSEXP, SEXP ASEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(hp_trend(x, A, lambda));
    return rcpp_result_gen;
END_RCPP
}
// gcv_single
double gcv_single(const arma::vec& x, const arma::vec& trend, double lambda, int T);
RcppExport SEXP _mhpfilter_gcv_single(SEXP xSEXP, SEXP trendSEXP, SEXP lambdaSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(gcv_single(x, trend, lambda, T));
    return rcpp_result_gen;
END_RCPP
}
// mhp_core
List mhp_core(const arma::vec& x, int max_lambda);
RcppExport SEXP _mhpfilter_mhp_core(SEXP xSEXP, SEXP max_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type max_lambda(max_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhp_core(x, max_lambda));
    return rcpp_result_gen;
END_RCPP
}
// hp_core
List hp_core(const arma::vec& x, double lambda);
RcppExport SEXP _mhpfilter_hp_core(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(hp_core(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// mhp_batch
List mhp_batch(const arma::mat& X, int max_lambda);
RcppExport SEXP _mhpfilter_mhp_batch(SEXP XSEXP, SEXP max_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type max_lambda(max_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhp_batch(X, max_lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mhpfilter_build_K", (DL_FUNC) &_mhpfilter_build_K, 1},
    {"_mhpfilter_hp_trend", (DL_FUNC) &_mhpfilter_hp_trend, 3},
    {"_mhpfilter_gcv_single", (DL_FUNC) &_mhpfilter_gcv_single, 4},
    {"_mhpfilter_mhp_core", (DL_FUNC) &_mhpfilter_mhp_core, 2},
    {"_mhpfilter_hp_core", (DL_FUNC) &_mhpfilter_hp_core, 2},
    {"_mhpfilter_mhp_batch", (DL_FUNC) &_mhpfilter_mhp_batch, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mhpfilter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
