# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_K <- function(T) {
    .Call(`_mhpfilter_build_K`, T)
}

hp_trend <- function(x, A, lambda) {
    .Call(`_mhpfilter_hp_trend`, x, A, lambda)
}

gcv_single <- function(x, trend, lambda, T) {
    .Call(`_mhpfilter_gcv_single`, x, trend, lambda, T)
}

mhp_core <- function(x, max_lambda) {
    .Call(`_mhpfilter_mhp_core`, x, max_lambda)
}

hp_core <- function(x, lambda) {
    .Call(`_mhpfilter_hp_core`, x, lambda)
}

mhp_batch <- function(X, max_lambda) {
    .Call(`_mhpfilter_mhp_batch`, X, max_lambda)
}

